/**
 * Parses embedded JSON tool calls from text output generated by open-weights models
 * (such as Llama 3.3 / Nemotron on NVIDIA NIM or vLLM) that output tool invocations directly into content.
 */
export function parseEmbeddedToolCalls(rawText: string): {
  remainingText: string;
  toolCalls: Array<{ id: string; name: string; input: Record<string, unknown> }>;
} {
  const toolCalls: Array<{ id: string; name: string; input: Record<string, unknown> }> = [];
  let remainingText = rawText;

  // 1. Tag format: <tool_call> ... </tool_call>
  const xmlRegex = /<tool_call>([\s\S]*?)<\/tool_call>/gi;
  let xmlMatch;
  while ((xmlMatch = xmlRegex.exec(rawText)) !== null) {
    try {
      const parsed = JSON.parse(xmlMatch[1].trim());
      const name = parsed.name || parsed.function?.name;
      const input = parsed.parameters || parsed.arguments || parsed.input || parsed.function?.arguments || {};
      if (name) {
        toolCalls.push({
          id: `call_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`,
          name,
          input: typeof input === "string" ? JSON.parse(input) : input,
        });
        remainingText = remainingText.replace(xmlMatch[0], "").trim();
      }
    } catch {}
  }

  // 2. Fenced markdown block format: ```json { "type": "function", ... } ```
  const fencedRegex = /```(?:json)?\s*(\{[\s\S]*?\})\s*```/gi;
  let fencedMatch;
  while ((fencedMatch = fencedRegex.exec(rawText)) !== null) {
    try {
      const parsed = JSON.parse(fencedMatch[1].trim());
      const name = parsed.name || (parsed.type === "function" && parsed.name ? parsed.name : parsed.function?.name);
      const input = parsed.parameters || parsed.arguments || parsed.input || parsed.function?.arguments || parsed.function?.parameters;
      if (name && input) {
        toolCalls.push({
          id: `call_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`,
          name,
          input: typeof input === "string" ? JSON.parse(input) : input,
        });
        remainingText = remainingText.replace(fencedMatch[0], "").trim();
      }
    } catch {}
  }

  // 3. Raw JSON object format:
  // e.g. {"type": "function", "name": "write_file", "parameters": {...}}
  // or {"name": "write_file", "parameters": {...}}
  if (toolCalls.length === 0) {
    const trimmed = rawText.trim();
    if (trimmed.startsWith("{") && trimmed.endsWith("}")) {
      try {
        const parsed = JSON.parse(trimmed);
        const name = parsed.name || (parsed.type === "function" && parsed.name ? parsed.name : parsed.function?.name);
        const input = parsed.parameters || parsed.arguments || parsed.input || parsed.function?.parameters || parsed.function?.arguments;
        if (name && input) {
          toolCalls.push({
            id: `call_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`,
            name,
            input: typeof input === "string" ? JSON.parse(input) : input,
          });
          remainingText = "";
        }
      } catch {}
    }
  }

  return { remainingText, toolCalls };
}
